### ISSUE TITLE
Handle Date types if type is string and format is date or date-time

### ISSUE THREAD

**Issue by Bomret** [atlantishealthcare/swagger-model-validator#86]
Currently the validation fails (`expireDate is required to be of type string`) if my model contains dates as `Date` type instead of `string`. As swagger 2.0 does not support own types for dates it would be nice if a type like the following:

```typescript
type Foo {
  expireDate: Date
}
```

with the following swagger 2.0 spec:

```yaml
Foo:
  properties:
    expireDate:
      type: string
      format: date-time
      example: '2017-06-12T00:00:00Z'
```

would not throw an error but be validated as a date. This is not an error but would be a nice convenience feature.
